![PUC Logo](http://www.inf.puc-rio.br/~inf1005/images/logo_di.png)

# Segundo Trabalho de Estruturas Discretas

>Professor: Prof. Marcus Vinicius S. Poggi de Aragão
- Este trabalho prático consiste em desenvolver códigos para diferentes algoritmos e estruturas de dados para resolver os problemas descritos e, principalmente, analisar o desempenho das implementações destes algoritmos com respeito ao tempo de CPU.

Integrantes do grupo:
- Gabriel Barbosa Diniz - 1511211
- Lucas Rodrigues - 1510848
- Mateus Ribeiro de Castro - 1213068

## Primeira Questão (Teorema 1)

> Dado um teorema do tipo: Sabe-se encontrar a árvore de peso máximo de G=(V,E) que contém o vértice 1 e possui K vértices; deseja-se encontrar o algoritmo correspondente que prove o teorema e teste o algoritmo em instâncias pequenas dos arquivos de dados fornecidos.

### Prova por Indução:

#### Caso Base:
> Começando com $k=1$, teremos uma árvore de um vértice só, sem arestas, o que resulta num peso total zerado.

#### Passo Indutivo em K:
> Procura-se $max \space (T(k))$ e somando os pesos das arestas de maior peso de cada uma das folhas. Para todos os nós, adicionam-se as arestas de maior peso com os vértices restantes, ou seja, $max \space (p_b \space t.q. \space b \space \epsilon \space (V - V_k))$

> Dessa forma, saberemos que adicionamos as arestas de maior peso, e à medida que se aumenta K basta incluirmos mais arestas de maior peso.

### (I) Implementação Python com Testes:

In [1]:
import numpy as np

# Algoritmo que recebe uma matriz de adjascências com os pesos das arestas e 

# OBS: Ao invés de usar vários parâmetros, procure usar o retorno múltiplo,
#      retornando o visited e a arvore. No caso, base tenta retornar uma matriz
#      vazia com o visited incluindo o primeiro vértice.

def HeavyTree(M,k):
    n = len(M)
    if(k > n or k < 0):
        print("K inválido!")
        return -1
    # Caso Base
    if(k == 1):
        visited = [0]
        tree = np.zeros((n,n))
        return tree, visited
    tree, visited = HeavyTree(M,k-1)
    B = [] # Vertices vizinhos a vertices visitados
    for i in range(n):
        if(i not in visited):     # Aqui temos a avaliação de todos os vertices
            for j in visited:     # não visitados que são vizinhos de vertices 
                if(M[i,j] != 0 and j not in B):  # visitados.
                    B = B + [i]
                    break
    biggest = 0
    new_v = 0
    old_v = 0
    for i in B:
        #new = np.max(M[i])
        for j in visited:
            if (M[i,j] > biggest):
                biggest = M[i,j]
                new_v = i
                old_v = j
    visited = visited + [new_v]
    #for i in range(n):
    #    if(M[new_v,i] == biggest):
    #        tree[i][new_v] = biggest
    #        tree[new_v][i] = biggest
    #        break
    tree[new_v][old_v] = biggest
    tree[old_v][new_v] = biggest
    return tree, visited

M = np.matrix([[0., 1., 1., 1.],
               [1., 0., 2., 1.],
               [1., 2., 0., 1.],
               [1., 1., 1., 0.]])
print(M[0,3])
n = len(M)
arvore, visited = HeavyTree(M,4)
print(arvore)


1.0
[[ 0.  1.  0.  1.]
 [ 1.  0.  2.  0.]
 [ 0.  2.  0.  0.]
 [ 1.  0.  0.  0.]]


## Primeira Questão (Teorema 1 - BÔNUS)

> Repita os itens anteriores para o teorema do tipo: Sabe-se encontrar a floresta de peso mínimo de G = (V, E) onde os componentes conexos possuem pelo menos K vértices.

### (I) Implementação Python com Testes:

## Segunda Questão (Teorema 2)

> Dado um teorema do tipo: Sabe-se determinar o prêmio máximo que o rei consegue coletar estando na posição (i,j) com q unidades restantes para consumir; apresente um algoritmo para determinar o caminho que o rei deve fazer para obter o maior total possível em prêmios e teste para um arquivo de dados com a estrutura apresentada.

### Prova por Indução:

> Caso Base: Com q = 0, temos um prêmio zero, pois não é possível se mover.


> Passo Indutivo: Procura-se o max(T(Q-qk) + pk) tal que q é o custo de se mover para a casa k e p é seu peso. Ou seja, a medida que vai aumentando o combustível disponível, aumentam as possibilidades de casas que podem ser alcançadas. Nesse ponto, precisamos procurar o arranjo máximo para que seja possível fazer essa transição. Lembrando que podemos ter sobras, então procuramos quaisquer arranjos e procurando o maior valor possível.

### (I) Implementação Python com Testes:

In [2]:
import numpy as np

# Do capeta essa porra aqui! Início de uma resolução.

def PremioMax(M,Prizes,Weights,Q):
    if (Q < 0):
        print("Valor de combustível inválido")
        return
    if (Q == 0):
        path = []
        prize = 0
        return path, prize # Caso Base, parada da recursão
    n = len(M)
    maxPrize = 0
    maxPath = []
    for i in range(n):
        path, prize = PremioMax(M,Prizes,Weights,Q-Weights[i])
        prize = prize + Prizes[i]
        path = path + [i]
        if(prize > maxP):
            maxPrize = prize
            maxPath = path
    return maxPath, maxPrize

# Inicialização dos Valores de Instância

Q = 8

## Terceira Questão (Teorema 3)

> Considere um texto definido pelo vetor de caracteres T[1..n]. Deseja-se determinar todas as ocorrências do string s[1..m] em T. Desenvolva algoritmos com este objetivo que atendam as condições determinadas...

>(a) - Acha as instâncias de uma palavra num texto.

### (I) Implementação Python com Testes:

In [40]:
#def next(s, Table):
#    pos = 1 # Posição da Tabela
#    candidato = 0 # Indice de s do proximo caracter
#    Table[0] = -1
#    while(pos<len(s)){
#        if(s[pos] == s[candidato]){
#            Table[pos] = Table[candidato]
#            pos = pos + 1
#            candidato = candidato + 1
#        } else {
#            Table[pos] = candidato
#            candidato = T[candidato]
#            while(candidato >= 0 and s[pos] != s[cadidato]){
#                candidato = Table[candidato]
#            }
#        }
#        Table[pos] = candidato
#    }
    
#def FindString(s, T):
#    m = 0
#    i = 0
#    Table = np.zeros(len(s))
#    next(s, Table)
#    for j in range(len(s)):
#        letra = s[j]
#        n = 32 
#        if(T[j] > 64 and T[j] < 91):
#            letra = letra - n

def Transform(string):
    n = len(string)
    for i in range(n):
        if(maiuscula(string[i])):
            string[i] = chr(ord(string[i]) + 32)
    return string
            
def FindWord (text, word):
    text = Transform(text)
    word = Transform(word)
    i = 0
    j = 0
    f = len(text)
    n = len(word)
    letra = text[i]
    instances = []
    start = 0
    end = 0
    in_string = 0
    while(i<f):
        if(letra == word[0] and in_string == 0):
            j = 0
            start = i
            end = i
            in_string = 1
        if(in_string == 1 and letra != word[j]):
            in_string = 0
            start = 0
            end = 0
            j = 0            
        if(in_string == 1 and letra == word[j] and j != (n-1)):
            j = j + 1
            end = end + 1   
        if(in_string == 1 and letra == word[j] and j == (n-1)):
            instances = instances + [[start,end]]
            start = 0
            end = 0
            in_string = 0
        if(i == (f-1)):
            break
        i = i + 1
        letra = text[i]
    return instances

text = ['a','B','c','d','e','b','c','b','c','e','f']
word = ['B','c']

instances = FindWord(text,word)
print(instances)

[[1, 2], [5, 6], [7, 8]]
